// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("With.Extensions")]
[assembly: AssemblyDescriptionAttribute("Extension methods used to copy and update immutable classes (as copy and update record expression in F#).")]
[assembly: GuidAttribute("cb6c3a37-63bb-488b-8778-bd52d97007ff")]
[assembly: AssemblyProductAttribute("With.Extensions")]
[assembly: AssemblyCompanyAttribute("Emmanuel Horrent")]
[assembly: AssemblyCopyrightAttribute("Copyright © Emmanuel Horrent 2015")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
